const AI_DATA = [
  {id:'chatgpt',name:'ChatGPT / GPT-5',maker:'OpenAI · 2022',logo:'🟢',accent:'#10a37f',cats:'texto código voz imagem',badge:'#1 MAIS USADO',pct:95,
   desc:'O mais popular do mundo. Excelente para conversação, redação, código e tarefas gerais.',
   tags:['texto','código','voz','imagem'],
   about:'ChatGPT é baseado na arquitetura GPT-5 da OpenAI. Treinado em bilhões de textos com RLHF. Mais de 180 milhões de usuários mensais.',
   pros:['Interface mais intuitiva','Multimodal: texto, imagem, voz','Ecossistema enorme de plugins','Excelente uso geral'],
   cons:['Pode alucinar fatos','Custo elevado para BR','Sem acesso offline'],
   specs:[{l:'ANO',v:'2022'},{l:'EMPRESA',v:'OpenAI'},{l:'FREE',v:'Sim'},{l:'PRO',v:'$20/mês'},{l:'API',v:'Sim'},{l:'CONTEXTO',v:'128K tokens'}],
   url:'https://chat.openai.com'},

  {id:'claude',name:'Claude (Sonnet / Opus)',maker:'Anthropic · 2023',logo:'🟠',accent:'#cc785c',cats:'texto código',badge:'#1 EM CÓDIGO',pct:82,
   desc:'Líder em engenharia de software. Excelente para código, análise e documentos longos.',
   tags:['texto','código','análise','raciocínio'],
   about:'Claude foi criado pela Anthropic com "Constitutional AI". Lidera o SWE-bench com 80.9% em código. Contexto de 200K tokens.',
   pros:['#1 em código e engenharia','Honesto sobre limitações','Contexto de 200K tokens','Raciocínio técnico excepcional'],
   cons:['Sem geração de imagens','Limite no free','Menos plugins'],
   specs:[{l:'ANO',v:'2023'},{l:'EMPRESA',v:'Anthropic'},{l:'FREE',v:'Sim'},{l:'PRO',v:'$20/mês'},{l:'API',v:'Sim'},{l:'CONTEXTO',v:'200K tokens'}],
   url:'https://claude.ai'},

  {id:'gemini',name:'Gemini Pro / Ultra',maker:'Google DeepMind · 2023',logo:'🔵',accent:'#4285f4',cats:'texto pesquisa voz',badge:'MULTIMODAL',pct:78,
   desc:'Multimodal nativo: texto, imagem, áudio e vídeo. Contexto de 1 milhão de tokens.',
   tags:['texto','pesquisa','vídeo','voz','multimodal'],
   about:'Gemini do Google DeepMind. Integrado ao Search, Docs, Gmail, YouTube. Contexto de 1 milhão de tokens.',
   pros:['Contexto de 1M tokens','Integrado ao Google','Multimodal nativo','Pesquisa em tempo real'],
   cons:['Código menos preciso','Privacidade Google','Respostas às vezes genéricas'],
   specs:[{l:'ANO',v:'2023'},{l:'EMPRESA',v:'Google'},{l:'FREE',v:'Sim'},{l:'PRO',v:'$20/mês'},{l:'API',v:'Sim'},{l:'CONTEXTO',v:'1M tokens'}],
   url:'https://gemini.google.com'},

  {id:'llama',name:'Llama 3.3 (Meta)',maker:'Meta · 2023',logo:'🦙',accent:'#0668E1',cats:'texto código open-source',badge:'OPEN SOURCE',pct:65,
   desc:'Modelo open-source mais poderoso da Meta. 100% gratuito, pode rodar localmente.',
   tags:['texto','código','open-source'],
   about:'Llama da Meta é open-source. Você pode baixar e rodar localmente, sem pagar nada e com privacidade total.',
   pros:['100% gratuito','Roda localmente','Comunidade enorme','Customizável'],
   cons:['Requer hardware','Pior que GPT-5 no geral','Sem interface oficial'],
   specs:[{l:'ANO',v:'2023'},{l:'EMPRESA',v:'Meta AI'},{l:'LICENÇA',v:'Open Source'},{l:'CUSTO',v:'Grátis'},{l:'LOCAL',v:'Sim'},{l:'CONTEXTO',v:'128K tokens'}],
   url:'https://ollama.ai'},

  {id:'mistral',name:'Mistral Large',maker:'Mistral AI · 2023',logo:'🌊',accent:'#ff7000',cats:'texto código open-source',badge:'EUROPEIA',pct:55,
   desc:'Startup francesa com modelos eficientes. Mistral 7B superou modelos muito maiores.',
   tags:['texto','código','open-source'],
   about:'Mistral AI francesa focada em eficiência. O Mistral 7B é uma revolução: modelo pequeno que supera gigantes.',
   pros:['Modelos eficientes','Parte open-source','Empresa europeia (GDPR)','Boa relação custo/benefício'],
   cons:['Ecossistema menor','Interface menos polida','Raciocínio inferior ao GPT-5'],
   specs:[{l:'ANO',v:'2023'},{l:'ORIGEM',v:'França 🇫🇷'},{l:'FREE',v:'Sim'},{l:'PRO',v:'€14/mês'},{l:'OPEN',v:'Parcial'},{l:'CONTEXTO',v:'128K tokens'}],
   url:'https://mistral.ai'},

  {id:'deepseek',name:'DeepSeek V3',maker:'DeepSeek · 2024',logo:'🐋',accent:'#1a6cff',cats:'texto código open-source',badge:'TOP EM CÓDIGO',pct:60,
   desc:'IA chinesa que chocou o mundo: qualidade do GPT-5 sendo totalmente gratuita e open-source.',
   tags:['texto','código','open-source','raciocínio'],
   about:'DeepSeek V3 surpreendeu o mercado: gratuito, open-source e com performance comparável ao GPT-5. Excelente em matemática.',
   pros:['Gratuito e open-source','Excelente em math/código','Performance de nível GPT-5','Sem custo de API'],
   cons:['Empresa chinesa','Interface menos polida','Suporte PT-BR limitado'],
   specs:[{l:'ANO',v:'2024'},{l:'ORIGEM',v:'China 🇨🇳'},{l:'CUSTO',v:'Grátis'},{l:'OPEN',v:'Sim'},{l:'API',v:'Sim'},{l:'CONTEXTO',v:'64K tokens'}],
   url:'https://chat.deepseek.com'},

  {id:'grok',name:'Grok 4',maker:'xAI (Elon Musk) · 2023',logo:'⚡',accent:'#e11d48',cats:'texto pesquisa',badge:'TEMPO REAL',pct:55,
   desc:'Integrado ao X (Twitter), acessa dados em tempo real. Direto e sem filtros excessivos.',
   tags:['texto','pesquisa','notícias','tempo real'],
   about:'Grok da xAI de Elon Musk. Acessa tweets e notícias em tempo real. Mais direto que os concorrentes.',
   pros:['Dados em tempo real','Menos filtros','Forte para tendências','Integrado ao X'],
   cons:['Menos preciso em ciências','Pode ser polêmico','Ecossistema menor'],
   specs:[{l:'ANO',v:'2023'},{l:'EMPRESA',v:'xAI'},{l:'FREE',v:'Limitado'},{l:'PRO',v:'$16/mês'},{l:'API',v:'Sim'},{l:'CONTEXTO',v:'128K tokens'}],
   url:'https://grok.com'},

  {id:'midjourney',name:'Midjourney V7',maker:'Midjourney Inc · 2022',logo:'🎨',accent:'#7c3aed',cats:'imagem',badge:'#1 IMAGENS',pct:70,
   desc:'Líder em geração de imagens artísticas. Transforma texto em arte fotorrealista ou estilizada.',
   tags:['imagem','arte','design','difusão'],
   about:'Midjourney usa difusão para criar imagens de texto. A melhor qualidade artística do mercado.',
   pros:['Qualidade artística top','Comunidade no Discord','Estilos personalizáveis','Referências de imagem'],
   cons:['Sem plano grátis','Via Discord','Ruim em texto nas imagens'],
   specs:[{l:'ANO',v:'2022'},{l:'EMPRESA',v:'Midjourney Inc'},{l:'FREE',v:'Trial'},{l:'BÁSICO',v:'$10/mês'},{l:'API',v:'Beta'},{l:'TIPO',v:'Difusão'}],
   url:'https://midjourney.com'},

  {id:'stablediffusion',name:'Stable Diffusion',maker:'Stability AI · 2022',logo:'🖌️',accent:'#9333ea',cats:'imagem open-source',badge:'IMAGEM OPEN',pct:58,
   desc:'O Midjourney do open-source. Rode localmente no seu PC, completamente grátis.',
   tags:['imagem','open-source','arte'],
   about:'Stable Diffusion roda localmente, é gratuito e tem comunidade enorme criando modelos e estilos.',
   pros:['100% gratuito','Roda localmente','Enorme variedade de estilos','Sem censura'],
   cons:['Requer GPU','Configuração técnica','Qualidade menor que Midjourney'],
   specs:[{l:'ANO',v:'2022'},{l:'EMPRESA',v:'Stability AI'},{l:'LICENÇA',v:'Open Source'},{l:'CUSTO',v:'Grátis'},{l:'LOCAL',v:'Sim'},{l:'TIPO',v:'Difusão'}],
   url:'https://stability.ai'},

  {id:'dalle',name:'DALL-E 3',maker:'OpenAI · 2023',logo:'🖼️',accent:'#ec4899',cats:'imagem',badge:'INTEGRADO GPT',pct:60,
   desc:'Gerador de imagens da OpenAI, integrado ao ChatGPT Plus. Segue instruções com precisão.',
   tags:['imagem','openai'],
   about:'DALL-E 3 é integrado ao ChatGPT Plus. Melhor que Midjourney para seguir instruções precisas.',
   pros:['Integrado ao ChatGPT','Segue prompts detalhados','Bom em texto nas imagens','Seguro'],
   cons:['Qualidade artística menor','Filtros rígidos','Sem plano dedicado'],
   specs:[{l:'ANO',v:'2023'},{l:'EMPRESA',v:'OpenAI'},{l:'ACESSO',v:'ChatGPT Plus'},{l:'PREÇO',v:'$20/mês'},{l:'API',v:'Sim'},{l:'TIPO',v:'Difusão'}],
   url:'https://openai.com/dall-e-3'},

  {id:'copilot',name:'GitHub Copilot',maker:'Microsoft / OpenAI · 2021',logo:'💻',accent:'#f59e0b',cats:'código',badge:'#1 DEVS',pct:73,
   desc:'IA de código mais usada. Integrada ao VSCode, autocompleta funções inteiras. FREE para estudantes! 🎓',
   tags:['código','vscode','autocompletar'],
   about:'GitHub Copilot integra aos editores. Estudantes conseguem grátis com o GitHub Student Pack!',
   pros:['Grátis para estudantes!','Integração no VSCode','Autocompletar em tempo real','Suporta +20 linguagens'],
   cons:['Requer editor','Pode ter bugs','Dados enviados'],
   specs:[{l:'ANO',v:'2021'},{l:'EMPRESA',v:'Microsoft'},{l:'ESTUDANTE',v:'🆓 Grátis!'},{l:'PRO',v:'$10/mês'},{l:'EDITORES',v:'VSCode++'},{l:'LINGUAGENS',v:'+20'}],
   url:'https://github.com/features/copilot'},

  {id:'cursor',name:'Cursor AI',maker:'Anysphere · 2023',logo:'🖱️',accent:'#6366f1',cats:'código',badge:'EDITOR IA',pct:62,
   desc:'Editor de código com IA que entende todo o seu projeto. Edita múltiplos arquivos ao mesmo tempo.',
   tags:['código','editor'],
   about:'Cursor é um fork do VSCode com IA profunda. Entende o projeto inteiro — refatora múltiplos arquivos.',
   pros:['Entende o projeto inteiro','Edita múltiplos arquivos','Baseado no VSCode','Free tier generoso'],
   cons:['Pago para uso intenso','Precisa de conexão','Curva de aprendizado'],
   specs:[{l:'ANO',v:'2023'},{l:'EMPRESA',v:'Anysphere'},{l:'FREE',v:'Sim'},{l:'PRO',v:'$20/mês'},{l:'BASE',v:'VSCode'},{l:'CONTEXTO',v:'Projeto inteiro'}],
   url:'https://cursor.sh'},

  {id:'perplexity',name:'Perplexity AI',maker:'Perplexity · 2022',logo:'🔍',accent:'#06b6d4',cats:'pesquisa texto',badge:'PESQUISA',pct:48,
   desc:'Motor de busca com IA. Responde com fontes reais em tempo real. Ideal para pesquisa.',
   tags:['pesquisa','fontes','tempo real'],
   about:'Perplexity combina LLM com busca em tempo real, sempre citando fontes verificadas.',
   pros:['Sempre cita fontes','Dados em tempo real','Ótimo para pesquisa','Interface limpa'],
   cons:['Pouco criativo','Fraco em código','Respostas curtas'],
   specs:[{l:'ANO',v:'2022'},{l:'EMPRESA',v:'Perplexity AI'},{l:'FREE',v:'Sim'},{l:'PRO',v:'$20/mês'},{l:'FONTES',v:'Sempre'},{l:'TEMPO REAL',v:'Sim'}],
   url:'https://perplexity.ai'},

  {id:'runway',name:'Runway ML',maker:'Runway · 2018',logo:'🎬',accent:'#14b8a6',cats:'vídeo imagem',badge:'#1 VÍDEOS',pct:45,
   desc:'Líder em geração de vídeos com IA. Usado por estúdios de cinema e criadores de conteúdo.',
   tags:['vídeo','imagem','criativo'],
   about:'Runway Gen-3 cria vídeos de alta qualidade a partir de texto ou imagem. Muito usado na indústria criativa.',
   pros:['Melhor qualidade em vídeo IA','Ferramentas criativas','Usado por profissionais','Interface amigável'],
   cons:['Caro para uso intenso','Vídeos curtos','Requer créditos'],
   specs:[{l:'ANO',v:'2018'},{l:'EMPRESA',v:'Runway'},{l:'FREE',v:'Sim'},{l:'PRO',v:'$12/mês'},{l:'TIPO',v:'Vídeo IA'},{l:'RESOLUÇÃO',v:'1080p'}],
   url:'https://runwayml.com'},

  {id:'elevenlabs',name:'ElevenLabs',maker:'ElevenLabs · 2022',logo:'🎙️',accent:'#22c55e',cats:'voz',badge:'#1 VOZ',pct:52,
   desc:'Líder em síntese de voz. Clone sua voz, crie narrações ultra-realistas em dezenas de idiomas.',
   tags:['voz','áudio'],
   about:'ElevenLabs cria vozes ultra-realistas, clona vozes reais e gera áudio em +30 idiomas.',
   pros:['Voz mais realista','Clonagem de voz','+30 idiomas','Bom suporte em PT-BR'],
   cons:['Caro em volume','Questões éticas','Latência em tempo real'],
   specs:[{l:'ANO',v:'2022'},{l:'EMPRESA',v:'ElevenLabs'},{l:'FREE',v:'Sim'},{l:'STARTER',v:'$5/mês'},{l:'IDIOMAS',v:'+30'},{l:'CLONAGEM',v:'Sim'}],
   url:'https://elevenlabs.io'},

  {id:'sora',name:'Sora',maker:'OpenAI · 2024',logo:'🎥',accent:'#f97316',cats:'vídeo',badge:'VÍDEO OpenAI',pct:40,
   desc:'Gerador de vídeos da OpenAI. Cria vídeos realistas de até 1 minuto com física real.',
   tags:['vídeo'],
   about:'Sora entende física real e cria movimentos de câmera complexos. Um dos mais avançados para vídeo.',
   pros:['Qualidade impressionante','Entende física real','Da OpenAI','Até 1 minuto'],
   cons:['Só no ChatGPT Pro ($200)','Custo elevado','Geração lenta'],
   specs:[{l:'ANO',v:'2024'},{l:'EMPRESA',v:'OpenAI'},{l:'ACESSO',v:'ChatGPT Pro'},{l:'PREÇO',v:'$200/mês'},{l:'DURAÇÃO',v:'até 60s'},{l:'TIPO',v:'Vídeo difusão'}],
   url:'https://sora.com'},

  {id:'gemma',name:'Gemma 3',maker:'Google DeepMind · 2024',logo:'💎',accent:'#34d399',cats:'texto código open-source',badge:'GOOGLE OPEN',pct:42,
   desc:'Versão open-source do Google. Modelos leves que rodam em PCs comuns com boa performance.',
   tags:['texto','código','open-source'],
   about:'Gemma é a família open-source do Google. Disponível em 2B a 27B parâmetros. Eficiente em hardware modesto.',
   pros:['Open-source do Google','Roda em hardware modesto','Boa qualidade','Gratuito'],
   cons:['Inferior ao Gemini Pro','Menos documentação','Comunidade menor que Llama'],
   specs:[{l:'ANO',v:'2024'},{l:'EMPRESA',v:'Google'},{l:'LICENÇA',v:'Open Source'},{l:'CUSTO',v:'Grátis'},{l:'LOCAL',v:'Sim'},{l:'TAMANHO',v:'2B–27B'}],
   url:'https://ai.google.dev/gemma'},

  {id:'qwen',name:'Qwen 2.5',maker:'Alibaba Cloud · 2023',logo:'☁️',accent:'#f59e0b',cats:'texto código open-source',badge:'ALIBABA',pct:44,
   desc:'Modelo da Alibaba com alta performance em código. Open-source e muito forte em matemática.',
   tags:['texto','código','open-source'],
   about:'Qwen 2.5 da Alibaba é competitivo com Llama e Mistral, especialmente forte em código e matemática.',
   pros:['Excelente custo-benefício','Open-source','Forte em código','Performance competitiva'],
   cons:['Empresa chinesa','Suporte PT-BR limitado','Menos conhecido no BR'],
   specs:[{l:'ANO',v:'2023'},{l:'EMPRESA',v:'Alibaba'},{l:'LICENÇA',v:'Apache 2.0'},{l:'CUSTO',v:'Grátis'},{l:'CONTEXTO',v:'128K tokens'},{l:'CÓDIGO',v:'Excelente'}],
   url:'https://qwen.ai'},

  {id:'copilot365',name:'Copilot (Microsoft 365)',maker:'Microsoft · 2023',logo:'🪟',accent:'#0078d4',cats:'texto código',badge:'MS OFFICE IA',pct:50,
   desc:'IA integrada ao Word, Excel, PowerPoint e Teams. Gera documentos e resume reuniões.',
   tags:['texto','código','produtividade'],
   about:'Copilot for Microsoft 365 integra IA ao Office. Resume emails, cria slides, analisa planilhas.',
   pros:['Integrado ao Office 365','Resume reuniões Teams','Gera slides e planilhas','Contexto organizacional'],
   cons:['Caro ($30/usuário)','Requer Microsoft 365','Dependência MS'],
   specs:[{l:'ANO',v:'2023'},{l:'EMPRESA',v:'Microsoft'},{l:'PREÇO',v:'$30/mês'},{l:'REQUER',v:'MS 365'},{l:'BASE',v:'GPT-4'},{l:'FOCO',v:'Produtividade'}],
   url:'https://copilot.microsoft.com'},

  {id:'perplexity',name:'Perplexity AI',maker:'Perplexity · 2022',logo:'🔍',accent:'#06b6d4',cats:'pesquisa texto',badge:'PESQUISA',pct:48,
   desc:'Motor de busca com IA. Responde com fontes reais em tempo real. Ideal para pesquisa.',
   tags:['pesquisa','fontes','tempo real'],
   about:'Perplexity combina LLM com busca em tempo real, sempre citando fontes verificadas.',
   pros:['Sempre cita fontes','Dados em tempo real','Ótimo para pesquisa','Interface limpa'],
   cons:['Pouco criativo','Fraco em código','Respostas curtas'],
   specs:[{l:'ANO',v:'2022'},{l:'EMPRESA',v:'Perplexity AI'},{l:'FREE',v:'Sim'},{l:'PRO',v:'$20/mês'},{l:'FONTES',v:'Sempre'},{l:'TEMPO REAL',v:'Sim'}],
   url:'https://perplexity.ai'},
];

const GLOSS_TERMS = [
  {t:'LLM',d:'Large Language Model — modelo treinado em bilhões de textos. A base do ChatGPT, Claude, Gemini.'},
  {t:'Transformer',d:'Arquitetura criada pelo Google em 2017. Base de praticamente todos os modelos modernos de IA.'},
  {t:'Token',d:'Pedaço de texto processado pela IA (~4 caracteres). Modelos têm limites de tokens por conversa.'},
  {t:'Prompt',d:'O texto que você envia para a IA. Um bom prompt leva a respostas muito melhores.'},
  {t:'RLHF',d:'Reinforcement Learning from Human Feedback — humanos avaliam respostas e ensinam o modelo a ser útil.'},
  {t:'Alucinação',d:'Quando a IA inventa fatos com confiança. Problema em todos os modelos. Sempre verifique informações importantes.'},
  {t:'Embeddings',d:'Representação matemática de texto em vetores. Permite à IA entender similaridade de significado.'},
  {t:'Fine-tuning',d:'Especializar um modelo genérico num domínio específico usando dados menores e específicos.'},
  {t:'RAG',d:'Retrieval-Augmented Generation — a IA busca informações externas antes de responder, reduzindo alucinações.'},
  {t:'Contexto',d:'Quantidade de texto que a IA "lembra" numa conversa. Mais contexto = conversas mais longas e precisas.'},
  {t:'Open Source',d:'Modelos cujo código e pesos são públicos. Qualquer um pode baixar, modificar e usar. Ex: Llama, Mistral.'},
  {t:'Parâmetros',d:'Os "neurônios" de um modelo. GPT-3 tem 175B. Mais parâmetros geralmente = modelo mais capaz.'},
  {t:'Multimodal',d:'IA que processa múltiplos tipos: texto, imagem, áudio e vídeo. Gemini e GPT-4o são multimodais.'},
  {t:'Difusão',d:'Técnica para gerar imagens. Começa com ruído aleatório e limpa guiado pelo texto até criar imagem.'},
  {t:'Agente de IA',d:'IA que não só responde, mas executa ações: navega na web, cria arquivos, roda código autonomamente.'},
  {t:'Temperatura',d:'Controla a criatividade da IA. Temperatura 0 = determinístico. Alta = mais criativo e aleatório.'},
  {t:'Constitutional AI',d:'Método da Anthropic onde a IA aprende princípios éticos e auto-avalia suas respostas.'},
  {t:'SWE-bench',d:'Benchmark que mede capacidade da IA em resolver bugs reais do GitHub. Referência para avaliar IAs de código.'},
  {t:'API',d:'Interface que permite programadores integrar IAs nos apps. A maioria dos grandes modelos oferece API.'},
  {t:'Benchmark',d:'Teste padronizado para medir performance de modelos. Permite comparações objetivas entre sistemas.'},
  {t:'GPT',d:'Generative Pre-trained Transformer — arquitetura da OpenAI. Base do ChatGPT.'},
  {t:'Vetor',d:'Representação numérica de dados. Textos similares têm vetores próximos, permitindo busca semântica.'},
];
