export const AI_DATA = [
  {id:'chatgpt',name:'ChatGPT / GPT-5',maker:'OpenAI · 2022',logo:'🟢',accent:'#10a37f',cats:'texto código voz imagem',badge:'#1 MAIS USADO',pct:95,
   desc:'O mais popular do mundo. Excelente para conversação, redação, código e tarefas gerais.',
   tags:['texto','código','voz','imagem'],
   about:'ChatGPT é baseado na arquitetura GPT-5 da OpenAI. Mais de 180 milhões de usuários mensais.',
   pros:['Interface mais intuitiva','Multimodal: texto, imagem, voz','Ecossistema enorme','Excelente uso geral'],
   cons:['Pode alucinar fatos','Custo elevado para BR','Sem acesso offline'],
   specs:[{l:'ANO',v:'2022'},{l:'EMPRESA',v:'OpenAI'},{l:'FREE',v:'Sim'},{l:'PRO',v:'$20/mês'},{l:'API',v:'Sim'},{l:'CONTEXTO',v:'128K tokens'}],
   url:'https://chat.openai.com'},

  {id:'claude',name:'Claude (Sonnet / Opus)',maker:'Anthropic · 2023',logo:'🟠',accent:'#cc785c',cats:'texto código',badge:'#1 EM CÓDIGO',pct:82,
   desc:'Líder em engenharia de software. Excelente para código, análise e documentos longos.',
   tags:['texto','código','análise','raciocínio'],
   about:'Claude foi criado pela Anthropic com Constitutional AI. Lidera o SWE-bench com 80.9% em código.',
   pros:['#1 em código','Honesto sobre limitações','Contexto de 200K tokens','Raciocínio excepcional'],
   cons:['Sem geração de imagens','Limite no free','Menos plugins'],
   specs:[{l:'ANO',v:'2023'},{l:'EMPRESA',v:'Anthropic'},{l:'FREE',v:'Sim'},{l:'PRO',v:'$20/mês'},{l:'API',v:'Sim'},{l:'CONTEXTO',v:'200K tokens'}],
   url:'https://claude.ai'},

  {id:'gemini',name:'Gemini Pro / Ultra',maker:'Google DeepMind · 2023',logo:'🔵',accent:'#4285f4',cats:'texto pesquisa voz',badge:'MULTIMODAL',pct:78,
   desc:'Multimodal nativo: texto, imagem, áudio e vídeo. Contexto de 1 milhão de tokens.',
   tags:['texto','pesquisa','vídeo','voz'],
   about:'Gemini do Google DeepMind. Integrado ao Search, Docs, Gmail. Contexto de 1M de tokens.',
   pros:['Contexto de 1M tokens','Integrado ao Google','Multimodal nativo','Pesquisa em tempo real'],
   cons:['Código menos preciso','Privacidade Google','Respostas genéricas'],
   specs:[{l:'ANO',v:'2023'},{l:'EMPRESA',v:'Google'},{l:'FREE',v:'Sim'},{l:'PRO',v:'$20/mês'},{l:'API',v:'Sim'},{l:'CONTEXTO',v:'1M tokens'}],
   url:'https://gemini.google.com'},

  {id:'llama',name:'Llama 3.3 (Meta)',maker:'Meta · 2023',logo:'🦙',accent:'#0668E1',cats:'texto código open-source',badge:'OPEN SOURCE',pct:65,
   desc:'Modelo open-source mais poderoso da Meta. 100% gratuito, pode rodar localmente.',
   tags:['texto','código','open-source'],
   about:'Llama da Meta é open-source. Rode localmente, sem pagar nada, com privacidade total.',
   pros:['100% gratuito','Roda localmente','Comunidade enorme','Customizável'],
   cons:['Requer hardware','Pior que GPT-5 no geral','Sem interface oficial'],
   specs:[{l:'ANO',v:'2023'},{l:'EMPRESA',v:'Meta AI'},{l:'LICENÇA',v:'Open Source'},{l:'CUSTO',v:'Grátis'},{l:'LOCAL',v:'Sim'},{l:'CONTEXTO',v:'128K tokens'}],
   url:'https://ollama.ai'},

  {id:'deepseek',name:'DeepSeek V3',maker:'DeepSeek · 2024',logo:'🐋',accent:'#1a6cff',cats:'texto código open-source',badge:'TOP EM CÓDIGO',pct:60,
   desc:'IA chinesa que chocou o mundo: qualidade do GPT-5 sendo totalmente gratuita e open-source.',
   tags:['texto','código','open-source'],
   about:'DeepSeek V3 é gratuito, open-source e com performance comparável ao GPT-5.',
   pros:['Gratuito e open-source','Excelente em código','Performance GPT-5','Sem custo de API'],
   cons:['Empresa chinesa','Interface menos polida','Suporte PT-BR limitado'],
   specs:[{l:'ANO',v:'2024'},{l:'ORIGEM',v:'China 🇨🇳'},{l:'CUSTO',v:'Grátis'},{l:'OPEN',v:'Sim'},{l:'API',v:'Sim'},{l:'CONTEXTO',v:'64K tokens'}],
   url:'https://chat.deepseek.com'},

  {id:'grok',name:'Grok 4',maker:'xAI · 2023',logo:'⚡',accent:'#e11d48',cats:'texto pesquisa',badge:'TEMPO REAL',pct:55,
   desc:'Integrado ao X (Twitter), acessa dados em tempo real. Direto e sem filtros excessivos.',
   tags:['texto','pesquisa','notícias'],
   about:'Grok da xAI de Elon Musk. Acessa tweets e notícias em tempo real.',
   pros:['Dados em tempo real','Menos filtros','Forte para tendências','Integrado ao X'],
   cons:['Menos preciso em ciências','Pode ser polêmico','Ecossistema menor'],
   specs:[{l:'ANO',v:'2023'},{l:'EMPRESA',v:'xAI'},{l:'FREE',v:'Limitado'},{l:'PRO',v:'$16/mês'},{l:'API',v:'Sim'},{l:'CONTEXTO',v:'128K tokens'}],
   url:'https://grok.com'},

  {id:'midjourney',name:'Midjourney V7',maker:'Midjourney Inc · 2022',logo:'🎨',accent:'#7c3aed',cats:'imagem',badge:'#1 IMAGENS',pct:70,
   desc:'Líder em geração de imagens artísticas. Transforma texto em arte fotorrealista.',
   tags:['imagem','arte','design'],
   about:'Midjourney usa difusão para criar imagens. A melhor qualidade artística do mercado.',
   pros:['Qualidade artística top','Comunidade enorme','Estilos personalizáveis','Referências de imagem'],
   cons:['Sem plano grátis','Via Discord','Ruim em texto nas imagens'],
   specs:[{l:'ANO',v:'2022'},{l:'EMPRESA',v:'Midjourney Inc'},{l:'FREE',v:'Trial'},{l:'BÁSICO',v:'$10/mês'},{l:'API',v:'Beta'},{l:'TIPO',v:'Difusão'}],
   url:'https://midjourney.com'},

  {id:'copilot',name:'GitHub Copilot',maker:'Microsoft · 2021',logo:'💻',accent:'#f59e0b',cats:'código',badge:'#1 DEVS',pct:73,
   desc:'IA de código mais usada. Integrada ao VSCode. FREE para estudantes! 🎓',
   tags:['código','vscode'],
   about:'GitHub Copilot integra aos editores. Estudantes conseguem grátis com o GitHub Student Pack!',
   pros:['Grátis para estudantes!','Integração no VSCode','Autocompletar em tempo real','Suporta +20 linguagens'],
   cons:['Requer editor','Pode ter bugs','Dados enviados'],
   specs:[{l:'ANO',v:'2021'},{l:'EMPRESA',v:'Microsoft'},{l:'ESTUDANTE',v:'🆓 Grátis!'},{l:'PRO',v:'$10/mês'},{l:'EDITORES',v:'VSCode++'},{l:'LINGUAGENS',v:'+20'}],
   url:'https://github.com/features/copilot'},

  {id:'perplexity',name:'Perplexity AI',maker:'Perplexity · 2022',logo:'🔍',accent:'#06b6d4',cats:'pesquisa texto',badge:'PESQUISA',pct:48,
   desc:'Motor de busca com IA. Responde com fontes reais em tempo real.',
   tags:['pesquisa','fontes','tempo real'],
   about:'Perplexity combina LLM com busca em tempo real, sempre citando fontes verificadas.',
   pros:['Sempre cita fontes','Dados em tempo real','Ótimo para pesquisa','Interface limpa'],
   cons:['Pouco criativo','Fraco em código','Respostas curtas'],
   specs:[{l:'ANO',v:'2022'},{l:'EMPRESA',v:'Perplexity AI'},{l:'FREE',v:'Sim'},{l:'PRO',v:'$20/mês'},{l:'FONTES',v:'Sempre'},{l:'TEMPO REAL',v:'Sim'}],
   url:'https://perplexity.ai'},

  {id:'cursor',name:'Cursor AI',maker:'Anysphere · 2023',logo:'🖱️',accent:'#6366f1',cats:'código',badge:'EDITOR IA',pct:62,
   desc:'Editor de código com IA que entende todo o seu projeto. Edita múltiplos arquivos.',
   tags:['código','editor'],
   about:'Cursor é fork do VSCode com IA profunda. Entende o projeto inteiro.',
   pros:['Entende o projeto inteiro','Edita múltiplos arquivos','Baseado no VSCode','Free tier generoso'],
   cons:['Pago para uso intenso','Precisa de conexão','Curva de aprendizado'],
   specs:[{l:'ANO',v:'2023'},{l:'EMPRESA',v:'Anysphere'},{l:'FREE',v:'Sim'},{l:'PRO',v:'$20/mês'},{l:'BASE',v:'VSCode'},{l:'CONTEXTO',v:'Projeto inteiro'}],
   url:'https://cursor.sh'},
]

export const GLOSS_TERMS = [
  {t:'LLM',d:'Large Language Model — modelo treinado em bilhões de textos. A base do ChatGPT, Claude, Gemini.'},
  {t:'Transformer',d:'Arquitetura criada pelo Google em 2017. Base de todos os modelos modernos de IA.'},
  {t:'Token',d:'Pedaço de texto processado pela IA (~4 caracteres). Modelos têm limites de tokens por conversa.'},
  {t:'Prompt',d:'O texto que você envia para a IA. Um bom prompt leva a respostas muito melhores.'},
  {t:'RLHF',d:'Reinforcement Learning from Human Feedback — humanos avaliam respostas e ensinam o modelo a ser útil.'},
  {t:'Alucinação',d:'Quando a IA inventa fatos com confiança. Sempre verifique informações importantes.'},
  {t:'Fine-tuning',d:'Especializar um modelo genérico num domínio específico usando dados menores e específicos.'},
  {t:'RAG',d:'Retrieval-Augmented Generation — a IA busca informações externas antes de responder.'},
  {t:'Contexto',d:'Quantidade de texto que a IA lembra numa conversa. Mais contexto = conversas mais longas.'},
  {t:'Open Source',d:'Modelos cujo código e pesos são públicos. Qualquer um pode baixar e usar. Ex: Llama, Mistral.'},
  {t:'Parâmetros',d:'Os neurônios de um modelo. GPT-3 tem 175B. Mais parâmetros = modelo mais capaz.'},
  {t:'Multimodal',d:'IA que processa múltiplos tipos: texto, imagem, áudio e vídeo.'},
  {t:'Difusão',d:'Técnica para gerar imagens. Começa com ruído e limpa guiado pelo texto.'},
  {t:'Agente de IA',d:'IA que age autonomamente: navega na web, cria arquivos, roda código.'},
  {t:'Temperatura',d:'Controla a criatividade da IA. 0 = determinístico. Alta = mais criativo.'},
  {t:'API',d:'Interface que permite programadores integrar IAs nos apps.'},
  {t:'Benchmark',d:'Teste padronizado para medir performance de modelos de IA.'},
  {t:'Embeddings',d:'Representação matemática de texto em vetores para busca semântica.'},
  {t:'Constitutional AI',d:'Método da Anthropic onde a IA aprende princípios éticos e auto-avalia respostas.'},
  {t:'SWE-bench',d:'Benchmark que mede capacidade da IA em resolver bugs reais do GitHub.'},
]